### ISSUE TITLE
Unable to find pyang.py

### ISSUE THREAD

**Issue by katdiam** [att/yang-design-studio#2]
Got "Unable to find pyang.py" when trying to create any file under "ATT-YANG".

**Comment by kd6913att** [comment]
PYANG must be installed from https://github.com/mbj4668/pyang
See documentation: https://github.com/att/yang-design-studio/blob/master/Docs/%5BFIRST%5DDependency_Installation_Guide-YANG-Design-Studio_v1.5.pdf
